import dotenv from "dotenv";
dotenv.config();

import { db } from "./drizzle";
import { packagingTypes } from "./schemas/packagingTypes";
import { products } from "./schemas/product";

const sellerId = "caba5b78-3e91-49c8-9f15-18490d1a46a7";

async function seed() {
  // 1) seed packaging types
  const insertedPackaging = await db
    .insert(packagingTypes)
    .values([
      { name: "Recyclable Paper", packagingScore: "9.5" },
      { name: "Biodegradable Plastic", packagingScore: "8.0" },
      { name: "Reusable Glass", packagingScore: "9.0" },
      { name: "Compostable Bagasse", packagingScore: "8.8" },
      { name: "Minimal Packaging", packagingScore: "10.0" },
    ])
    .returning({ id: packagingTypes.id, name: packagingTypes.name });

  const packagingMap = Object.fromEntries(insertedPackaging.map((p) => [p.name, p.id]));

  // 2) seed products
  await db.insert(products).values([
    {
      title: "Eco-Friendly Notebook",
      brand: "EcoWrite",
      originalPrice: "5.99",
      discount: "0.00",
      description: "Made with 100% recycled paper.",
      images: ["https://example.com/notebook.jpg"],
      features: ["Recycled paper", "Hardcover", "Eco ink"],
      specifications: { pages: 200, weight: "0.5kg", size: "8×6 in" },
      category: "Stationery",
      inStock: 100,
      carbonImpact: "1.20",
      packagingTypeId: packagingMap["Recyclable Paper"],
      ecoTags: ["recycled", "sustainable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Organic Cotton T-Shirt",
      brand: "GreenWear",
      originalPrice: "19.99",
      discount: "0.00",
      description: "Soft and breathable organic cotton.",
      images: ["https://example.com/tshirt.jpg"],
      features: ["100% organic cotton", "Pre-shrunk", "Machine washable"],
      specifications: { sizes: "S–XL", weight: "0.2kg" },
      category: "Clothing",
      inStock: 50,
      carbonImpact: "2.50",
      packagingTypeId: packagingMap["Biodegradable Plastic"],
      ecoTags: ["organic", "biodegradable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard", "express"],
      sellerId,
    },
    {
      title: "Reusable Water Bottle",
      brand: "HydroGreen",
      originalPrice: "15.49",
      discount: "0.00",
      description: "Made of BPA-free stainless steel.",
      images: ["https://example.com/bottle.jpg"],
      features: ["18 oz capacity", "Double-wall insulation", "Leak-proof lid"],
      specifications: { capacity: "532ml", material: "Stainless steel" },
      category: "Lifestyle",
      inStock: 70,
      carbonImpact: "1.80",
      packagingTypeId: packagingMap["Reusable Glass"],
      ecoTags: ["reusable", "zero-waste"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Plant-Based Soap",
      brand: "NatureClean",
      originalPrice: "3.50",
      discount: "0.00",
      description: "Vegan and cruelty-free with compostable packaging.",
      images: ["https://example.com/soap.jpg"],
      features: ["Vegan", "Cruelty-free", "Moisturizing"],
      specifications: { weight: "100g", scent: "Lavender" },
      category: "Personal Care",
      inStock: 200,
      carbonImpact: "0.80",
      packagingTypeId: packagingMap["Compostable Bagasse"],
      ecoTags: ["vegan", "compostable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Bamboo Toothbrush",
      brand: "EcoBrush",
      originalPrice: "2.99",
      discount: "0.00",
      description: "Natural bamboo handle and recyclable bristles.",
      images: ["https://example.com/toothbrush.jpg"],
      features: ["Bamboo handle", "Recyclable bristles", "Ergonomic grip"],
      specifications: { bristleType: "Soft", length: "7in" },
      category: "Personal Care",
      inStock: 150,
      carbonImpact: "0.50",
      packagingTypeId: packagingMap["Minimal Packaging"],
      ecoTags: ["bamboo", "low-waste"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "LED Light Bulb",
      brand: "EcoLight",
      originalPrice: "4.25",
      discount: "0.00",
      description: "Energy-efficient 10W LED bulb.",
      images: ["https://example.com/bulb.jpg"],
      features: ["10W", "800 lm", "25 000 hr lifespan"],
      specifications: { wattage: "10W", colorTemp: "3000K" },
      category: "Electronics",
      inStock: 120,
      carbonImpact: "0.90",
      packagingTypeId: packagingMap["Recyclable Paper"],
      ecoTags: ["energy-saving", "long-life"],
      supportsEcoPackaging: true,
      deliveryType: ["standard", "overnight"],
      sellerId,
    },
    {
      title: "Biodegradable Trash Bags",
      brand: "GreenBin",
      originalPrice: "6.75",
      discount: "0.00",
      description: "Certified home-compostable.",
      images: ["https://example.com/trashbags.jpg"],
      features: ["Home compostable", "Strength-tested", "Large 30 gal"],
      specifications: { capacity: "30 gal", material: "PLA blend" },
      category: "Home Essentials",
      inStock: 80,
      carbonImpact: "1.10",
      packagingTypeId: packagingMap["Biodegradable Plastic"],
      ecoTags: ["compostable", "biodegradable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Eco-Friendly Cleaning Spray",
      brand: "SafeClean",
      originalPrice: "7.99",
      discount: "0.00",
      description: "Non-toxic, safe for pets and children.",
      images: ["https://example.com/cleaner.jpg"],
      features: ["Non-toxic", "Biodegradable formula", "Multi-surface"],
      specifications: { volume: "500ml", scent: "Citrus" },
      category: "Home Essentials",
      inStock: 90,
      carbonImpact: "1.30",
      packagingTypeId: packagingMap["Reusable Glass"],
      ecoTags: ["non-toxic", "reusable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Organic Tea Bags",
      brand: "GreenLeaf",
      originalPrice: "4.99",
      discount: "0.00",
      description: "Compostable tea bags with minimal outer packaging.",
      images: ["https://example.com/tea.jpg"],
      features: ["Organic blend", "Biodegradable filter", "Box of 50"],
      specifications: { quantity: 50, weightPerBag: "2g" },
      category: "Food",
      inStock: 110,
      carbonImpact: "0.70",
      packagingTypeId: packagingMap["Compostable Bagasse"],
      ecoTags: ["organic", "compostable"],
      supportsEcoPackaging: true,
      deliveryType: ["standard"],
      sellerId,
    },
    {
      title: "Minimalist Phone Case",
      brand: "EcoTech",
      originalPrice: "9.95",
      discount: "0.00",
      description: "Made from recycled TPU with eco-friendly ink.",
      images: ["https://example.com/case.jpg"],
      features: ["Recycled TPU", "Thin design", "Wireless-charging safe"],
      specifications: { material: "Recycled TPU", thickness: "1.2 mm" },
      category: "Electronics",
      inStock: 65,
      carbonImpact: "1.00",
      packagingTypeId: packagingMap["Minimal Packaging"],
      ecoTags: ["recycled", "minimal"],
      supportsEcoPackaging: true,
      deliveryType: ["standard", "express"],
      sellerId,
    },
  ]);

  console.log("✅ Seed completed successfully.");
}

seed().catch((err) => {
  console.error("❌ Error during seed:", err);
  process.exit(1);
});
